site_name: Lathunden

theme:
  name: material
  language: sv
  palette:
    # Låter eleverna växla mellan mörkt och ljust läge
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Byt till mörkt läge
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Byt till ljust läge

# Menyn för din lathund
nav:
  - Hem: index.md
  - Webbutveckling:
      - Webbutveckling: webbutveckling/_index.md
      - HTML Grunder: webbutveckling/html-structure.md
      - CSS Grunder: webbutveckling/css-structure.md
  - Programmering:
      - Programmering: programmering/_index.md
  - Git:
      - Skapa nytt Repo: git/Skapa nytt Repo.md